# Generated by Django 2.2.15 on 2020-09-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connect',
            old_name='userName',
            new_name='user',
        ),
    ]
